services:
  kgem-api:
    build:
      context: ./kgem_api
    container_name: kgem-api
    ports:
      - "8000:8000"
    volumes:
      - ./kgem_api/models:/app/models 
    restart: always

  recommendation_service:
    build:
      context: ./recommendation_service
    container_name: recommendation_service
    ports:
      - "8002:8002"
    volumes:
      - ./recommendation_service/models:/app/models
    environment:
      - KGE_API_BASE=http://kgem-api:8000
    depends_on:
      - kgem-api
    restart: always

  demo:
    build:
      context: ./recommendation_service
    container_name: kgem-recommender-demo
    command: ["uv", "run", "streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
    ports:
      - "8501:8501"
    environment:
      - RECOMMENDATION_API_BASE=http://recommendation_service:8002
    depends_on:
      - recommendation_service
    restart: always
